### ISSUE TITLE
Map not rendering with css

### ISSUE THREAD

**Issue by mrunks** [darnton/LeafletBlazor#13]
I am using a Web Assembly with hosted project and when trying copy the example, I noticed that when I try to set the reference to leaflet.css in index.html that the page is blank with no map rendering.  If I take it out then parts of the map start to render. Any suggestions what would be causing this ? There are no errors showing up on the console.

**Comment by bryanrcarlson** [comment]
Double check that the div containing the map has a height property defined. It's been a few months since I played around with the example, but I think I ran into a similar issue.

**Comment by mrunks** [comment]
Thanks for some reason its not reading the #testMap style.  But if I make a new class such as .mapDisplay in the same css file and reference it in the class attribute it works.
